language: node_js

node_js:
  - lts/*

before_script:
  - npm run build:prod

install:
  - npm install

script:
  - npm run test
after_success:
  - npm run build

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
      branch: master
