language: node_js

node_js:
  - lts/*

before_install:
  - npm i -g npm@^6.0.0

script:
  - npm run test
after_success:
  - npm run build
  - npm run docs

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
      branch: master
