name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up node 14.14.0
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 14.14.0
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install node dependencies
      run: npm install
    - name: Build with NPM
      run: npm run build
    - name: Run tests
      run: npm run test
    - name: Report build status via Slack
      uses: act10ns/slack@v1
      if: always()
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
